services:
  docs:
    image: squidfunk/mkdocs-material:9
    container_name: studydocs_mkdocs
    working_dir: /docs
    volumes:
      - ./:/docs
    ports:
      - "8000:8000"
    command: >
      serve
      --dev-addr=0.0.0.0:8000


